hg_path_dict:
  {
    "hg19": "/home/d.gaillard/source/PEsWGS-alignment-snakemake/ref_genome/hg19.fa",
    "hg38noalt": "/home/d.gaillard/source/reference_genomes/hg38_no_alt/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna",
    "hg38full": "/home/d.gaillard/source/reference_genomes/hg38_full/hg38.fa",
  }
